// Relative import to be able to reuse the C sources.
// See the comment in ../native_zip.podspec for more information.
#include "../../src/my_atomic_int_max.c"
#include "../../src/my_compress.c"
#include "../../src/my_file.c"
#include "../../src/my_file_posix.c"
#include "../../src/my_hashmap.c"
#include "../../src/my_message_queue.c"
#include "../../src/my_task_notify.c"
#include "../../src/my_queue.c"
#include "../../src/my_tar.c"
#include "../../src/my_thread.c"
#include "../../src/my_threadpool.c"
#include "../../src/my_utils.c"
#include "../../src/my_zlib.c"
#include "../../src/my_zip_utils.c"
#include "../../src/my_zip.c"
#include "../../src/my_zip_async.c"
#include "../../src/native_zip.c"
